### ISSUE TITLE
Inconsitent results between table 2 and fig 9

### ISSUE THREAD

**Issue by urchade** [universal-ner/universal-ner#11]
Dear authors

Thank you for the nice paper and dataset. I have some question regarding the results

Result on table 2 and fig 9 are inconsistent:
for instance, for chat-gpt:
- restaurant get 32.8 (table 2) and 33.8 (fig 9)
- Movie get 5.3 (table 2) and 6.3 (fig 9)

it look like there is a score difference of exactly 1 every time. Could you please clarify that ?

**Comment by wzhouad** [comment]
Thank you for bringing this discrepancy to our attention. Upon revisiting our code, we found an error in our plotting script of Fig. 9, where the ax.text command was mistakenly using x+1 for the value instead of the correct value x. We will make the necessary corrections in our next preprint version.
